name: 🐛 Bug Report
description: Report a bug in the Terraform module
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure module with...
        2. Run terraform apply...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: What version of Terraform are you using?
      placeholder: "1.5.0"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of this module are you using?
      placeholder: "1.2.0"
    validations:
      required: true

  - type: dropdown
    id: provider-version
    attributes:
      label: Hetzner Cloud Provider Version
      description: Which version of the Hetzner Cloud provider are you using?
      options:
        - "~> 1.50.0"
        - "~> 1.49.0"
        - "~> 1.48.0"
        - "Other (specify in additional context)"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Terraform Configuration
      description: Please share your Terraform configuration (remove sensitive data)
      render: hcl
      placeholder: |
        module "immich" {
          source = "..."
          
          # Required variables
          hcloud_token         = "..."
          ssh_public_keys      = ["..."]
          s3_access_key_id     = "..."
          s3_secret_access_key = "..."
          s3_bucket_name       = "..."
          
          # Optional variables
          # Your configuration here
        }

  - type: textarea
    id: logs
    attributes:
      label: Terraform Output/Logs
      description: Please paste any relevant Terraform output or error logs
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here