name: 🚀 Feature Request
description: Suggest a new feature for the Terraform module
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: I have also considered...

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Simple variable/output addition"
        - "Medium - New resource or significant logic change"
        - "High - Major architectural change"
        - "Unknown - Need investigation"

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature affect?
      options:
        - label: "Infrastructure resources (servers, networks, etc.)"
        - label: "Security configuration"
        - label: "Cost optimization"
        - label: "Immich application setup"
        - label: "Storage configuration (JuiceFS/B2)"
        - label: "SSL/Domain configuration"
        - label: "Documentation"
        - label: "Examples"

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request